src/Netnr.ResponseFramework/Netnr.ResponseFramework/Components/ButtonViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;

namespace Netnr.ResponseFramework.ViewComponents
{
    /// <summary>
    /// 按钮视图组件
    /// </summary>
    public class ButtonViewComponent : ViewComponent
    {
        /// <summary>
        /// 按钮组件
        /// </summary>
        /// <returns></returns>
        public IViewComponentResult Invoke()
        {
            string current_url = "/" + RouteData.Values["controller"]?.ToString() + "/" + RouteData.Values["action"]?.ToString();

            //按钮列表
            var listBtn = new List<Domain.SysButton>();

            //根据路由反查页面对应的菜单
            //所有链接保持小写
            var moMenu = Func.Common.QuerySysMenuList(x => x.SmUrl == current_url.ToLower()).FirstOrDefault();
            if (moMenu != null)
            {
                //登录用户的角色信息
                var luri = Func.Common.LoginUserRoleInfo(HttpContext);
                if (luri != null && !string.IsNullOrWhiteSpace(luri.SrButtons))
                {
                    //角色配置的按钮
                    var joRole = JObject.Parse(luri.SrButtons);
                    //根据菜单ID取对应的按钮
                    string btns = joRole[moMenu.SmId].ToStringOrEmpty();
                    if (!string.IsNullOrWhiteSpace(btns))
                    {
                        var btnids = btns.Split(',').ToList();

                        //根据按钮ID取按钮
                        listBtn = Func.Common.QuerySysButtonList(x => btnids.Contains(x.SbId));
                    }
                }
            }

            return View(listBtn);
        }
    }
}

src/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Shared/_BaseViewPartial.cshtml
@model string
@if (Model != "0")
{
    <!--列表-->
    <div class="row gridBox">
        <div id="PGrid1" class="col-md-12">
            <div id="Grid1" class="loadingimg"></div>
        </div>
    </div>
}

<!--配置表格-->
<script src="/js/inlay/configtable.js" asp-append-version="true"></script>
<!--搜索模块-->
<script src="/js/inlay/configquery.js" asp-append-version="true"></script>
<!--基础包-->
<script src="/js/inlay/baseviewpartial.js" asp-append-version="true"></script>
<!--引入页面JS-->
@{
    var jssrc = $"/js/{ViewContext.RouteData.Values["controller"].ToString().ToLower()}/{ViewContext.RouteData.Values["action"].ToString().ToLower()}.js";
    var jspath = GlobalTo.WebRootPath + jssrc;
    if (System.IO.File.Exists(jspath))
    {
        <script src='@jssrc' asp-append-version="true"></script>
    }
}

src/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Shared/_FormItemPartial.cshtml
@model IGrouping<int, SysTableConfig>

@foreach (var item in Model)
{
    var maxlen = item.FormMaxlength == -1 ? "" : item.FormMaxlength.ToString();
    var coln = 6;
    switch (item.FormSpan)
    {
        case 2: coln = 12; break;
        case 3: coln = 4; break;
        case 4: coln = 8; break;
    }

    <div class='col-md-@coln col-sm-6 @(item.FormHide>=1?"hidden":"")'>
        <div class="form-group">
            <label class='control-label @(item.FormRequired==1?"required":"")'>@item.ColTitle</label>
            <div>
                @if ("checkbox".Contains(item.FormType))
                {
                    <label class="checkbox">
                        <input type="checkbox" @(item.FormValue == "1" ? "checked" : "") value="1" id="@item.ColField" name="@item.ColField" data-type="@item.FormType" data-query="@item.ColQuery" data-url="@item.FormUrl" placeholder="@item.FormPlaceholder" />
                        @item.FormText
                    </label>
                }
                else if ("datetime".Contains(item.FormType))
                {
                    <input type='text' id="@item.ColField" name="@item.ColField" class="form-control" value="@item.FormValue" data-type="@item.FormType" data-query="@item.ColQuery" data-url="@item.FormUrl" placeholder="@item.FormPlaceholder" maxlength="@maxlen" />
                }
                else if ("modal".Contains(item.FormType))
                {
                    <input type='text' id="@item.ColField" name="@item.ColField" class="form-control" value="@item.FormValue" data-type="@item.FormType" data-query="@item.ColQuery" data-url="@item.FormUrl" placeholder="@item.FormPlaceholder" maxlength="@maxlen" />
                    <i class="fa fa-search form-control-feedback"></i>
                }
                else if ("textarea".Equals(item.FormType))
                {
                    <textarea id="@item.ColField" name="@item.ColField" class="form-control area-height" data-type="@item.FormType" data-query="@item.ColQuery" data-url="@item.FormUrl" placeholder="@item.FormPlaceholder" maxlength="@maxlen">@item.FormValue</textarea>
                }
                else if ("password".Equals(item.FormType))
                {
                    <input type='password' id="@item.ColField" name="@item.ColField" class="form-control" value="@item.FormValue" data-type="@item.FormType" data-query="@item.ColQuery" data-url="@item.FormUrl" placeholder="@item.FormPlaceholder" maxlength="@maxlen" />
                }
                else if ("file".Equals(item.FormType))
                {
                    <input type='file' id="@item.ColField" class="form-control" data-type="@item.FormType" data-query="@item.ColQuery" data-url="@item.FormUrl" />
                    <input type="hidden" id="hid_@item.ColField" name="@item.ColField" value="@item.FormValue" />
                    @if (!string.IsNullOrWhiteSpace(item.FormPlaceholder))
                    {
                        <p class="help-block">@item.FormPlaceholder</p>
                    }
                }
                else
                {
                    <input type='text' id="@item.ColField" name="@item.ColField" class="form-control" value="@item.FormValue" data-type="@item.FormType" data-query="@item.ColQuery" data-url="@item.FormUrl" placeholder="@item.FormPlaceholder" maxlength="@maxlen" />
                }
            </div>
        </div>
    </div>
}

src/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="chrome=1,IE=edge" />
    <meta charset="utf-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <partial name="_QuotePartial" model="@("bootstrap.css,fa.css,jquery.js,bootstrap.js,easyui,z.css,z.js")" />
</head>
<body>
    <div class="container-fluid">
        @await Component.InvokeAsync("Button")
        <div id="myBody">
            @RenderBody()
        </div>
    </div>
</body>
</html>

src/Netnr.ResponseFramework/Netnr.ResponseFramework/Views/Shared/_QuotePartial.cshtml
@model string
@{
    var listQuote = Model.Split(',').ToList();
}
@foreach (var item in listQuote)
{
    switch (item)
    {
        case "fa.css":
            <link href="https://code.bdstatic.com/npm/font-awesome@4.7.0/css/font-awesome.min.css" rel="stylesheet">
            break;

        case "jquery.js":
            <script src="https://code.bdstatic.com/npm/jquery@1.12.4/dist/jquery.min.js"></script>
            break;

        case "bootstrap.css":
            <link href="https://code.bdstatic.com/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" rel="stylesheet">
            break;

        case "bootstrap.js":
            <script src="https://code.bdstatic.com/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js"></script>
            break;

        case "easyui":
            <link href="https://code.bdstatic.com/npm/netnr-cdn@0.0.1/libs/jquery-easyui/1.9.0/themes/metro/easyui.css" rel="stylesheet" />
            <script src="https://code.bdstatic.com/npm/netnr-cdn@0.0.1/libs/jquery-easyui/1.9.0/jquery.easyui.min.js"></script>
            break;

        case "ace.css":
            <link href="https://code.bdstatic.com/npm/netnr-cdn@0.0.1/libs/acenav/20200108/ace.min.css" rel="stylesheet" asp-append-version="true" />
            <link href="https://code.bdstatic.com/npm/netnr-cdn@0.0.1/libs/acenav/20200108/ace-skins.min.css" rel="stylesheet" asp-append-version="true" async />
            break;

        case "ace.js":
            <script src="https://code.bdstatic.com/npm/netnr-cdn@0.0.1/libs/acenav/20200108/ace.min.js" asp-append-version="true"></script>
            break;

        case "z.css":
            <link href="/css/z.css" rel="stylesheet" asp-append-version="true" />
            break;

        case "z.js":
            <script src="/js/z.js" asp-append-version="true"></script>
            break;

        case "init.js":
            <script src="/js/init.js" asp-append-version="true"></script>
            break;

        case "ckeditor.js":
            <script src="https://code.bdstatic.com/npm/ckeditor@4.12.1/ckeditor.js"></script>
            break;

        case "monaco-editor":
            <script src="https://code.bdstatic.com/npm/monaco-editor@0.19.3/min/vs/loader.js"></script>
            <script>
                require.config({
                    paths: { vs: "https://code.bdstatic.com/npm/monaco-editor@0.19.3/min/vs" },
                    'vs/nls': { availableLanguages: { '*': 'zh-cn' } }
                });
            </script>
            break;

        case "loading":
            <div id="LoadingMask" style="position: fixed; top: 0; left: 0; bottom: 0; right: 0; background-color: white; z-index: 9999; background-image:url('/images/loading.svg');background-repeat:no-repeat;background-position:48% 45%"></div>
            break;
    }
}